name: Ruby RSpec

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install os dependencies
      - name: Install os dependencies
        run: sudo apt-get update && sudo apt-get install -y exiftool

      # Set up Ruby 3.2
      - name: Set up Ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      # Install dependencies (including Rake and RSpec)
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # Run Rake task for RSpec
      - name: Run RSpec with Rake
        run: |
          bundle exec rake
